#!/bin/bash
# Quick test to verify auto-reload is working

TEST_FILE="/tmp/test_vim_sync.txt"

echo "=== QUICK VIM AUTO-RELOAD TEST ==="
echo ""
echo "Step 1: Create test file"
echo "Hello World - Initial" > "$TEST_FILE"
echo "   Created: $TEST_FILE"
echo ""
echo "Step 2: Open in TWO tmux panes:"
echo "   Pane 1: vim $TEST_FILE"
echo "   Pane 2: vim $TEST_FILE"
echo ""
echo "Step 3: In your .vimrc, make sure you have:"
echo "   :source ~/.vimrc"
echo ""
echo "Step 4: Test the setup:"
echo "   a) In Pane 1, type: i<Enter>Line from pane 1<Esc>:w"
echo "   b) Switch to Pane 2"
echo "   c) Move cursor or wait 0.5 seconds"
echo "   d) You should see the new line appear!"
echo ""
echo "If still not working, run IN VIM:"
echo "   :set autoread?"
echo "   :echo &updatetime"
echo "   :autocmd FocusGained"
echo ""
echo "Expected output:"
echo "   autoread -> should show 'autoread'"
echo "   updatetime -> should show 500"
echo "   autocmd FocusGained -> should show your autocmd"
